### ISSUE TITLE
负魔上限没法设置

### ISSUE THREAD

**Issue by ClancyNGC1277** [Iseason2000/DeEnchantment#10]
即使
LevelUnlimited: false
玩家依旧能从过于昂贵中附魔物品
提示语也是 |附魔书| 本次附魔花费xxx
另外装的更多附魔插件有ECO附魔，并按照说明完成兼容

**Comment by Iseason2000** [comment]
已在新版本中添加相关配置，请更新完之后手动添加配置
```TEXT
# 是否允许铁砧过于昂贵仍能附魔，如果开启突破等级上限建议开启
AllowTooExpensive: false
```
