### ISSUE TITLE
使用此插件导致其他附魔插件附魔物品描述异常

### ISSUE THREAD

**Issue by AdminHcat** [Iseason2000/DeEnchantment#11]
![Screenshot_2022-02-07-04-37-38-839_com discord](https://user-images.githubusercontent.com/50044729/152700835-9ff8a85c-8a6b-4fc5-86ad-8db0d9e90d93.jpg)
使用excellent enchants附魔插件的附魔书在铁砧中附魔物品，附魔后的物品不会显示非原版附魔的附魔名称和描述信息
经排除，该问题是由负魔书引起的，禁用负魔书后此问题不再复现，望开发者尽快修复此问题

**Comment by Iseason2000** [comment]
收到，将会尽快修复

**Comment by Iseason2000** [comment]
1.1.7版本已修复
