### ISSUE TITLE
物品在铁砧内合并后使部分附魔属性缺失

### ISSUE THREAD

**Issue by AdminHcat** [Iseason2000/DeEnchantment#12]
物品在铁砧内合并后将会导致部分附魔属性消失，如图

未加载负魔书插件
![image](https://user-images.githubusercontent.com/50044729/152749871-4e4cf280-2269-4a20-b770-580404a77437.png)

已加载负魔书插件
![image](https://user-images.githubusercontent.com/50044729/152749886-293d7966-a996-4398-a384-568be6d3fda3.png)

这可能仍然是一个与Excellent enchants插件的兼容性问题

**Comment by Iseason2000** [comment]
[DeEnchantment-1.1.8-all.zip](https://github.com/Iseason2000/DeEnchantment/files/8016122/DeEnchantment-1.1.8-all.zip)
我做了尝试性修复，请下载完 在配置里添加 
``` text
# 如果你有其他附魔插件修改了铁砧的机制请开启此项
AnvilConflict: false
```
将 AnvilConflict 设置为true再次尝试

**Comment by AdminHcat** [comment]
> [DeEnchantment-1.1.8-all.zip](https://github.com/Iseason2000/DeEnchantment/files/8016122/DeEnchantment-1.1.8-all.zip) 我做了尝试性修复，请下载完 在配置里添加
> 
> ```
> # 如果你有其他附魔插件修改了铁砧的机制请开启此项
> AnvilConflict: false
> ```
> 
> 将 AnvilConflict 设置为true再次尝试

是的按你所说的在配置文件对此配置项进行了添加并重启服务器，并没有解决此问题

**Comment by Iseason2000** [comment]
在我的测试中并没有问题，你可以加我qq：1347811744 提供详细信息
没有插件：
![image](https://user-images.githubusercontent.com/65019366/152913064-7e939b8c-5731-4469-9937-50821ad2cedc.png)
有插件：
![image](https://user-images.githubusercontent.com/65019366/152913093-1da92788-34a3-49af-8845-1cfb3e0e99d1.png)

**Comment by Iseason2000** [comment]
1.1.8 版本已修复
