### ISSUE TITLE
铁砧附魔后会移除全部附魔效果并且花费经验加1

### ISSUE THREAD

**Issue by DreamVoid** [Iseason2000/DeEnchantment#13]
**插件版本:** 1.2.2

**服务端版本：**  Purpur-1.18.2

### 问题描述
https://github.com/PurpurMC/Purpur/issues/924
移除插件后问题消失，因此判定是负魔书的问题

### 报错截图
见上

### 相关插件
N/A

### 如何重现问题
见上

**Comment by Iseason2000** [comment]
确认是bug，将尽快修复

**Comment by Iseason2000** [comment]
由于是使用的NBTAPI的bug，现已上报上游，等待上游修复后将修复此bug。

https://github.com/BananaPuncher714/NBTEditor/issues/20

如果你有其他附魔类的插件可以在配置里将 AnvilConflict 设置为 true 以使用其他插件的铁砧机制

**Comment by Iseason2000** [comment]
已支持1.18.2，请下载最新1.2.3版本
