### ISSUE TITLE
插件无法加载，输入命令后无反馈

### ISSUE THREAD

**Issue by chettestwef** [Iseason2000/DeEnchantment#14]
**插件版本:** 
deenchantment v1.2.6
**服务端版本：**
This server is running CraftBukkit version git-Spigot-9639cf7-4b9bc9d (MC: 1.16.1) (Implementing API version 1.16.1-R0.1-SNAPSHOT)
### 问题描述
插件无法加载，输入命令后无反馈
### 报错截图
![image](https://user-images.githubusercontent.com/99162086/161538307-b095dd64-fe74-4291-ac43-9c705a9dba9f.png)
[latest (31).log](https://github.com/Iseason2000/DeEnchantment/files/8409372/latest.31.log)

### 相关插件
Plugins (66): ServerMonitor, xiaoheiBind, SpawnLimit, PlaceholderAPI, deenchantment, MiraiMC, PiglinFix, AntiWorldFly, SkinsRestorer, Quests, TabCompleteFilter, ViaVersion, PlayerHeads, UBBDispenserShulkerBoxFixer, Trash, ClearLag, NoBedExplosions, AdvancedBan, WGAcheck, IronElevators, ProtocolLib, Obsidiantolava, LoginManager, MVdWPlaceholderAPI, Notbuild, LiteSignIn, AntiAttack, PermissionsEx, XiaoheiQSManger, xiaoheiPlayer, NoCommands, LangUtils, Vault, XiaoheiConsole, MiaoChat, JoinEventsPro, Matrix, HolographicDisplays, PlayerPoints, CratesLottery, AuctionHouse, ChestCommands, PlayerTitle, BossShopPro, PlayerVaults, WorldEdit, PlayerKits, Essentials, SX-Attribute, ColorMOTD, SuperLobby, BentoBox, AdvancedAchievements, HolographicPlaceholders, TAB, TimePerm, QuickShop, Slimefun, EcoPower, EssentialsSpawn, TitleManager, Multiverse-Core, ExoticGarden, AuthMe, KillerMoney, CMILib
### 如何重现问题
将插件置入plugins文件夹并启动服务器

**Comment by Iseason2000** [comment]
1.2.6版本由于更改了依赖加载方式，如果网络问题会导致无法加载，请使用1.2.5版本

**Comment by Iseason2000** [comment]
注意：本插件只支持1.16.4以上版本，1.16.1版本会导致一些负魔获取方式失效

**Comment by chettestwef** [comment]
谢谢，我已经成功载入1.2.5
![image](https://user-images.githubusercontent.com/99162086/161672269-47655f66-d1ba-44b3-9eac-a544b0e278c7.png)
那这个issues我关闭啦！
