### ISSUE TITLE
使用铁砧耐久2放到第二格会变成耐久3

### ISSUE THREAD

**Issue by RanWhite** [Iseason2000/DeEnchantment#15]
**插件版本:** 1.2.8

**服务端版本：**1.18.2

### 问题描述
使用铁砧耐久2放到第二格会变成耐久3

### 报错截图
https://s1.ax1x.com/2022/06/02/XNk0l8.png

### 相关插件
仅安装deenchantment，不安装的时候不会出现
### 如何重现问题
任何附魔+耐久2放入铁砧 耐久会变成3

**Comment by Iseason2000** [comment]
已 修复 https://github.com/Iseason2000/DeEnchantment/releases/tag/1.2.9
