### ISSUE TITLE
1.19适配

### ISSUE THREAD

**Issue by RanWhite** [Iseason2000/DeEnchantment#16]
**插件版本:** 
1.2.9
**服务端版本：**
1.19
### 问题描述
1.19适配

### 报错截图
无法使用铁砧附魔

**Comment by Iseason2000** [comment]
已修复铁砧使用问题，关于1.19的新负魔还在构思中，过阵子添加
https://github.com/Iseason2000/DeEnchantment/releases/tag/1.3.0

**Comment by RanWhite** [comment]
> 已修复铁砧使用问题，关于1.19的新负魔还在构思中，过阵子添加 https://github.com/Iseason2000/DeEnchantment/releases/tag/1.3.0

感谢！加鸡腿！

**Comment by Iseason2000** [comment]
已适配1.19 https://github.com/Iseason2000/DeEnchantment/releases/tag/2.0.0
请注意插件经过重构，配置大有不同，部分数据可以通过命令迁移,最好先看一下新的负魔描述
