### ISSUE TITLE
负魔无法合成更高等级及合成负魔失效问题

### ISSUE THREAD

**Issue by SkipM4** [Iseason2000/DeEnchantment#17]
**插件版本:** 
1.3.0
**服务端版本：**
Purpur 1.19 1699
### 问题描述
无法将两本刺穿IV合成为刺穿V
铁砧合成 粘液科技的自动附魔台均只能合成刺穿IV
使用指令给手中物品添加负魔后并不显示负魔属性，与其他附魔书敲在一起即显示
已有负魔装备在铁砧敲上其他属性附魔书后负魔属性还会显示但负魔的效果消失
### 报错截图
enchant 负魔
![圖片](https://user-images.githubusercontent.com/40311581/177561144-493f159b-d3f5-4cfb-8695-b5c2c1ba3b1c.png)
不显示负魔但有效果
![圖片](https://user-images.githubusercontent.com/40311581/177561123-529f5f47-b5dd-4194-a73f-e0671b583acd.png)
将负魔从装备上扒下来不显示
![圖片](https://user-images.githubusercontent.com/40311581/177561472-262c7c30-7577-435c-8eca-da350f2056dd.png)

### 相关插件
SlimeFun
### 如何重现问题
背叛3书
![圖片](https://user-images.githubusercontent.com/40311581/177562716-00195304-1b20-475b-8d57-4c6001dcda68.png)
不显示的经验反哺书
![圖片](https://user-images.githubusercontent.com/40311581/177562859-fff328c6-2aa5-47d9-a6c7-59d9b2813a86.png)
负魔正常显示
![圖片](https://user-images.githubusercontent.com/40311581/177562896-4871cc22-eda6-4bd7-801c-1b4ca8e28e1a.png)

带有负魔的三叉戟
![圖片](https://user-images.githubusercontent.com/40311581/177563127-bffad9a7-3c58-4679-b078-4381252b4b6c.png)
穿刺5附魔书
![圖片](https://user-images.githubusercontent.com/40311581/177563156-233331b0-1a76-4ad2-9f83-4b1bce45416b.png)
显示正常但所有负魔已失效的三叉戟
![圖片](https://user-images.githubusercontent.com/40311581/177563574-027ceca8-6b07-4921-80c6-ffc651f473e3.png)
测试原有负魔以及穿刺均失效（也就是说连正常附魔都失效了）
![圖片](https://user-images.githubusercontent.com/40311581/177564579-f72d5493-f690-4464-8243-37df09ec580b.png)
经测试此三叉戟需要三下打死溺尸，另一穿刺5三叉戟只需要两下

**Comment by Iseason2000** [comment]
显示问题是由于插件使用 lore 显示负魔，只能在可控范围内进行显示（比如铁砧、附魔台），但粘液科技不属于这个范围，下个版本将尝试对粘液科技进行适配

关于负魔失效的问题，是所有负魔都失效还是部分，有无报错 。请确保配置中的负魔 enable为true 并 de reload 重载

关于显示正常但负魔失效的，试试用nbt工具查看是否有对应负魔，可能是负魔被擦除了，但留下了lore  如果是这样请提供插件列表以排除问题

**Comment by SkipM4** [comment]
> 显示问题是由于插件使用 lore 显示负魔，只能在可控范围内进行显示（比如铁砧、附魔台），但粘液科技和ess的指令不属于这个范围，请使用插件自带的命令 de add 和 de give 给予负魔 。下个版本将尝试对粘液科技进行适配
> 
> 关于负魔失效的问题，是所有负魔都失效还是部分，有无报错 。请确保配置中的负魔 enable为true 并 de reload 重载
> 
> 关于显示正常但负魔失效的，试试用nbt工具查看是否有对应负魔，可能是负魔被擦除了，但留下了lore 如果是这样请提供插件列表以排除问题

敲上正常附魔后使用de add添加的负魔功能正常

普通铁剑 de add 引火烧身 铁砧敲上锋利5后引火烧身失效
此时服务端报错参见https://pastebin.com/QmMKtw3w

击退2铁剑 de add 亡灵救赎 正常 铁砧敲上火焰附加2后亡灵救赎失效
此时服务端报错参见https://pastebin.com/KxQkPsAT

精准采集铁镐 de add 经验反哺 正常 铁砧敲上效率5后经验反哺失效
此时服务端报错参见https://pastebin.com/tc804Upu

已测试 背叛 刺穿 引火烧身 亡灵救赎 经验反哺 彻底粉碎 水下窒息 均会失效
![圖片](https://user-images.githubusercontent.com/40311581/177700525-4fa4321b-b61c-4a6c-a776-4e13288d1bd6.png)
负魔的确只剩下了一行lore而不是附魔

DeEnchantment已启用全部负魔 config.yml内容参见https://pastebin.com/wWq3RzJM
插件列表
Plugins (45): AtLite, BanItem, BlockLocker, CatSeedLogin, ChatColor2, ChatImage, ChineseName, Chunky, CMILib, CoreProtect, DeadlyDisasters, DeEnchantment, EClean, Essentials, EssentialsChat, EssentialsSpawn, GroupManager, HiveChecker, HsRails, ItemNBTEdit, JukeBox, LiteAnnouncer, LiteItemShow, LiteSignIn, MarriageMaster, Multiverse-Core, NBTAPI, NekoMaid, NoteBlockAPI, OpenInv, PlaceholderAPI, PlugManX, ProtocolLib, QuickShop, Residence, ServerMonitor, SkinsRestorer, Slimefun, spark, Uniporter, Vault, ViaBackwards, ViaVersion, WorldEdit, HAProxyDetector

**Comment by Iseason2000** [comment]
已修复铁砧报错问题 https://github.com/Iseason2000/DeEnchantment/releases/tag/1.3.1
兼容粘液科技等待下个版本

**Comment by Iseason2000** [comment]
已适配粘液科技 https://github.com/Iseason2000/DeEnchantment/releases/tag/2.0.0
请注意插件经过重构，配置大有不同，部分数据可以通过命令迁移,最好先看一下新的负魔描述
