### ISSUE TITLE
将依赖jar放置在插件文件夹中，而不是工作目录

### ISSUE THREAD

**Issue by DreamVoid** [Iseason2000/DeEnchantment#19]
我觉得和插件有关的东西应该放在插件的文件夹里，放到别的地方看着不舒服。
腾讯等国产毒瘤已经滥用手机的存储了

既然插件要重构，有没有考虑把插件名称的大小写整一下

**Comment by Iseason2000** [comment]
> 我觉得和插件有关的东西应该放在插件的文件夹里，放到别的地方看着不舒服。
> 腾讯等国产毒瘤已经滥用手机的存储了
> 
> 既然插件要重构，有没有考虑把插件名称的大小写整一下

依赖下载功能使用的是spigot提供的接口，无法更改目录。
在服务端根目录的好处是不同插件可以共享依赖而不需要重复下载，于gradle或者maven的本地缓存一致。

你的需求在我重构代码换用自己的依赖下载模块之后可以实现

**Comment by Iseason2000** [comment]
插件已重构，指定依赖位置请修改plugin.yml

~~~ yaml
runtime-libraries:
  # If not defined, it will be 'libraries'
  # when start with @Plugin: will start with plugin data folder
  libraries-folder: 'libraries'
~~~

在libraries-folder中加入@Plugin 前缀则存放到插件的配置文件夹中
https://github.com/Iseason2000/DeEnchantment/releases/tag/2.0.0
请注意插件经过重构，配置大有不同，部分数据可以通过命令迁移,最好先看一下新的负魔描述
