### ISSUE TITLE
与另一款附魔插件「EcoEnchants」冲突

### ISSUE THREAD

**Issue by Shizuri23** [Iseason2000/DeEnchantment#2]
hi作者，我又找到个bug「应该是bug吧」
与EcoEnchants插件冲突，两者插件安装的情况下
附魔台最多原版+「负魔书」效果，EcoEnchants的附魔完全消失
如果将「负魔书」删去，EcoEnchants正常工作
<img width="188" alt="image" src="https://user-images.githubusercontent.com/46082179/125124622-faf26e00-e12a-11eb-9591-2f4041fc1f48.png">
图上是只安装了「EcoEnchants」的情况
<img width="174" alt="image" src="https://user-images.githubusercontent.com/46082179/125124809-41e06380-e12b-11eb-9e9f-0cfff9f17c18.png">
图上是两个插件都安装了的情况

**Comment by Iseason2000** [comment]
逻辑上修复了，但由于插件是付费插件，我无法测试，请帮我测试下
[DeEnchantment_Beta.zip](https://github.com/Iseason2000/DeEnchantment/files/6794671/DeEnchantment_Beta.zip)

**Comment by Iseason2000** [comment]
已修复 [](https://github.com/Iseason2000/DeEnchantment/releases/tag/1.0.5)
