### ISSUE TITLE
Paper1.19服务端无法加载注册负魔

### ISSUE THREAD

**Issue by SistineFibelKen** [Iseason2000/DeEnchantment#20]
**插件版本:** 

v1.3.1

**服务端版本：**

"git-Paper-41 (MC: 1.19)"

### 问题描述

插件能正常开启且加载，但无法载入任何的负附魔，显示注册(0/0)

### 报错截图

![Log](https://user-images.githubusercontent.com/57359004/179344354-250203f0-208b-4883-a58c-0ba778b7903c.jpg)

### 相关插件

无，只有DeEnchantment v1.3.1

### 如何重现问题

将插件放入plugin，下载组件，完成之后加载插件，没有注册任何负附魔

**Comment by Iseason2000** [comment]
请尝试手动使用 de reload 来注册负魔

**Comment by SistineFibelKen** [comment]
> 请尝试手动使用 de reload 来注册负魔

感谢，成功了，请问这个是插件的问题还是服务端核心的问题？

**Comment by Iseason2000** [comment]
这个问题属于偶发问题，目前无法确定源头，只能在出现时手动reload一下
