### ISSUE TITLE
附魔导致原本lore顺序出现错乱

### ISSUE THREAD

**Issue by RanWhite** [Iseason2000/DeEnchantment#23]
**插件版本** :  2.0.2
**服务端版本**: git-Paper-99 (MC: 1.19.1)

**bug描述**
放入铁砧和任何附魔导致原本的lore顺序错乱
貌似只有特定的lore才会触发具体原因未找到

你可以尝试一下我这个lore
把颜色符号去掉后无法复现

第一行 &c&l抽奖&f&l-&c&l限时活动
第二行 &c&l----&f&l属性&c&l----
第三行 &e&l真实伤害:6
第四行 &c&l------------

**报错截图
![D(VOA2_ 4}V9EB_H2}KSZ}Y](https://user-images.githubusercontent.com/69817107/182631461-fd833270-b605-49c9-a65b-331470a4948c.png)
**
![744C(6QK%DP~{@6@FL2$PWP](https://user-images.githubusercontent.com/69817107/182631467-0a277eb4-6e2f-4a2e-bff5-9802bd39d32b.png)

**Comment by Iseason2000** [comment]
由于bukkit自定义附魔在原版客户端没有对应的翻译键，所以附魔的显示用的是lore，默认是在第一行插入，我可以提供一个选项来手动更改插入负魔lore的位置

**Comment by RanWhite** [comment]
> 由于bukkit自定义附魔在原版客户端没有对应的翻译键，所以附魔的显示用的是lore，默认是在第一行插入，我可以提供一个选项来手动更改插入负魔lore的位置。 不过看你的图貌似没有负魔的存在，请将负魔插件停用再试试，以确定是负魔插件的原因

在没有负魔插件的时候 lore行数是正常显示的
![$K0AL SRP55DQLJLHJI9 L1](https://user-images.githubusercontent.com/69817107/182634803-29bcf6c8-6726-45f9-a5e6-e243ccc4134e.png)
![ASLQ2CH6U}IB8V35RY40VFL](https://user-images.githubusercontent.com/69817107/182634810-62d5143f-655d-427b-9012-071651b9c005.png)

**Comment by Iseason2000** [comment]
![image](https://user-images.githubusercontent.com/65019366/182635641-092dc6bf-ba74-4654-8006-38e55692dc07.png)
![image](https://user-images.githubusercontent.com/65019366/182635664-4fb1a000-a73e-4cdc-8ea3-b7c48a8744c3.png)
在我的测试中没有负魔也是这样的

**Comment by RanWhite** [comment]
> ![image](https://user-images.githubusercontent.com/65019366/182635641-092dc6bf-ba74-4654-8006-38e55692dc07.png) ![image](https://user-images.githubusercontent.com/65019366/182635664-4fb1a000-a73e-4cdc-8ea3-b7c48a8744c3.png) 在我的测试中没有负魔也是这样的

是的 你得用我一样的lore 我怀疑是颜色符号 我用其他lore无法复现

**Comment by RanWhite** [comment]
> > ![image](https://user-images.githubusercontent.com/65019366/182635641-092dc6bf-ba74-4654-8006-38e55692dc07.png) ![image](https://user-images.githubusercontent.com/65019366/182635664-4fb1a000-a73e-4cdc-8ea3-b7c48a8744c3.png) 在我的测试中没有负魔也是这样的
> 
> 是的 你得用我一样的lore 我怀疑是颜色符号 我用其他lore无法复现

第一行 &c&l抽奖&f&l-&c&l限时活动
第二行 &c&l----&f&l属性&c&l----
第三行 &e&l真实伤害:6
第四行 &c&l------------

**Comment by Iseason2000** [comment]
![image](https://user-images.githubusercontent.com/65019366/182637648-ca999bf2-3d73-458a-9c7e-1605d498d46c.png)
![image](https://user-images.githubusercontent.com/65019366/182637676-353aa623-ce42-459d-a32b-077fb3d536c9.png)
还是这样，你加我qq1347811744 聊吧，快一点

**Comment by Iseason2000** [comment]
已找到原因，稍后修复

**Comment by Iseason2000** [comment]
已修复 https://github.com/Iseason2000/DeEnchantment/releases/tag/2.0.3
