### ISSUE TITLE
服务器在启动时候默认加载全部附魔

### ISSUE THREAD

**Issue by RanWhite** [Iseason2000/DeEnchantment#24]
**插件版本** :  2.0.3
**服务端版本**: paper-1.19.1-99

**bug描述**
负魔即使在配置文件已经把enable设置false
但是在服务器启动时仍然加载了全部的负魔
需要手动reload插件才能正确的加载
这个问题自从2.0.0以后出现直到现在

**报错截图**
这是服务器启动时候的截图
![F ~L~HZL3C(TKHA43@0$88M](https://user-images.githubusercontent.com/69817107/182673115-cc1c1c12-16a0-4557-b1f2-c1a829e95473.png)
在没改任何配置文件的情况下reload 
![TNR~E$EB9SUZ N}I50CD1SN](https://user-images.githubusercontent.com/69817107/182673259-86831910-4a30-4682-a100-701366c196d8.png)
可以看到现在可以正常被加载了

**Comment by Iseason2000** [comment]
2.0.4版本已修复
