### ISSUE TITLE
指令无法使用和附魔描述消失

### ISSUE THREAD

**Issue by HowieHz** [Iseason2000/DeEnchantment#25]
**插件版本** :  2.0.4
**服务端版本**: purpur-1.19.1-1748

**背景描述**
先前使用的是1.3.1版本，为了兼容ecoenchants进行了作者在mcbbs中描述的设定（对config.yml进行设置，修改ecoenchants的lang.yml文件）
因为无法使用指令继承配置，所以使用的是2.0.4版默认的配置文件
![image](https://user-images.githubusercontent.com/94725606/182844714-6e75d507-0d7b-42f1-9d85-3c8187667ef2.png)

根据作者大大的回复，进行了ecoenchants的lang.yml文件的重置和服务器的重启，问题依旧

# **bug1**
指令无法使用

**bug1 报错截图**
![image](https://user-images.githubusercontent.com/94725606/182844002-8859fa87-33c2-415c-8994-d630a3ff3ce4.png)
并且也查询不到负魔书相关指令
![image](https://user-images.githubusercontent.com/94725606/182845778-11fda958-646d-417d-9a2c-2321247c1569.png)

# **bug2**
附魔名称消失，附魔描述消失

**bug2 报错截图**
![image](https://user-images.githubusercontent.com/94725606/182845301-a7ea1c5a-2caf-4cc6-93d7-8be2c9a4f51a.png)
![image](https://user-images.githubusercontent.com/94725606/182845338-df7e261c-f22c-45a9-9ce5-d26eac10bb79.png)

**其他信息**
ecoenchants开启了附魔描述

插件列表
![image](https://user-images.githubusercontent.com/94725606/182845934-0642009f-d00e-421d-a9b9-3e451a682fdd.png)

**Comment by Iseason2000** [comment]
是否有插件启用时输出的日志或者报错

**Comment by HowieHz** [comment]
![image](https://user-images.githubusercontent.com/94725606/182846996-287f62eb-eaf0-4219-ac54-4b76d9f53a86.png)
经过检查后发现唯一一处报错

**Comment by HowieHz** [comment]
> deenchantment reload

![image](https://user-images.githubusercontent.com/94725606/182847452-6db83b65-2bba-4d8c-a27a-7a201ed97818.png)
w完整的也无法使用

**Comment by HowieHz** [comment]
> > ![image](https://user-images.githubusercontent.com/94725606/182846996-287f62eb-eaf0-4219-ac54-4b76d9f53a86.png) 经过检查后发现唯一一处报错
> 
> 应该是我使用的ecoenchants API 版本与你的不一致导致的，请提供一下你的ecoenchants 用于测试

好的，https://wwp.lanzoul.com/iLGFi090ez6f

**Comment by Iseason2000** [comment]
我这边测试一切正常，请尝试更新eco及ecoenchants版本到最新版试试,我会尝试解决报错问题

**Comment by HowieHz** [comment]
> 我这边测试一切正常，请尝试更新eco及ecoenchants版本到最新版试试,我会尝试解决报错问题

好的，正在测试

**Comment by HowieHz** [comment]
**感谢作者大大**

**Comment by Iseason2000** [comment]
最终修复版为 2.0.5
