### ISSUE TITLE
经验使用/吃附魔属性

### ISSUE THREAD

**Issue by zihaoshijie** [Iseason2000/DeEnchantment#26]
**插件版本** :  2.0.0
**服务端版本**: purpur-1.19.1-1746

**bug描述**
1.本来经验只要1-3 现在需要14-16不等
2.例子：经验修补 饵钓2 钓鱼竿和 耐久3 海之眷顾3 饵钓2合成以后会自动删除海之眷顾3 而属性并不冲突

**重现步骤**
1. 放入两钓鱼竿
2. 经验异常
3. 附魔属性异常

**报错截图**
暂无，抱歉

**其他信息**

**Comment by Iseason2000** [comment]
请先尝试最新版的插件，目前是2.0.5因为其中改动过铁砧，如果还有问题我会修复

**Comment by zihaoshijie** [comment]
经验问题解决了吗

**Comment by Iseason2000** [comment]
> 经验问题解决了吗

因为你用的不是最新版，我不确定在最新版中有没有这个问题，所以我建议你使用最新版，还是出现问题我会尽快修复

**Comment by zihaoshijie** [comment]
我们用的是最新版本，实时更新 paper端口
腐竹已经和我确认了

**Comment by Iseason2000** [comment]
进过测试并未复现你的问题，请提供更多信息，我说的最新版本是负魔插件的版本，不是服务端的版本

没有装负魔插件的情况
![image](https://user-images.githubusercontent.com/65019366/183234788-028e640a-3b90-4b0a-95e2-309e532395b0.png)
![image](https://user-images.githubusercontent.com/65019366/183234792-97a29722-2995-4490-bbe4-eb605e2f1210.png)
![image](https://user-images.githubusercontent.com/65019366/183234797-0ee6a733-1663-42dc-9e22-9381ceab4bab.png)

装了负魔插件v2.0.5的情况
![image](https://user-images.githubusercontent.com/65019366/183234837-9d0eab98-3d33-4102-b1d7-900dd9b3f788.png)
![image](https://user-images.githubusercontent.com/65019366/183234842-079bcb6b-4c1d-443e-aaa4-9937ee4639d1.png)
![image](https://user-images.githubusercontent.com/65019366/183234853-dcded756-8b50-476c-8df8-298a0bcbc2d4.png)

**Comment by zihaoshijie** [comment]
emm,那就奇怪了，我们腐竹实时更新

**Comment by zihaoshijie** [comment]
因为你知道吧，我之前遇到过这个问题，然后我找我们管理把两个钓鱼竿给他，他给我一个完好的，现在怎么样我也不是很清楚，希望好了吧

**Comment by Iseason2000** [comment]
> 因为你知道吧，我之前遇到过这个问题，然后我找我们管理把两个钓鱼竿给他，他给我一个完好的，现在怎么样我也不是很清楚，希望好了吧

有没有可能是其他附魔类插件造成的

**Comment by zihaoshijie** [comment]
顺带问个问题，就是永存祝福1 是啥意思 除了他还有啥绿色良性魔咒吗

**Comment by Iseason2000** [comment]
> 顺带问个问题，就是永存祝福1 是啥意思 除了他还有啥绿色良性魔咒吗

![](https://user-images.githubusercontent.com/65019366/182375428-b02a48ea-8b45-49f2-b6b4-a425c46fd74a.png)

**Comment by zihaoshijie** [comment]
谢谢你
不然我至今搞不懂为啥我们服务器有人弓和机关枪一样

**Comment by zihaoshijie** [comment]
所以我们服有不掉落，永存祝福和灵魂绑定就是垃圾？

**Comment by Iseason2000** [comment]
> 所以我们服有不掉落，永存祝福和灵魂绑定就是垃圾？
在2.0.0版本起
永存祝福保护你的物品掉落物永不消失，会回到你身上
灵魂绑定 只有你能使用这个物品

**Comment by Iseason2000** [comment]
我在最新的2.0.6版本中修复了可能吃附魔的bug https://github.com/Iseason2000/DeEnchantment/releases/tag/2.0.6
