### ISSUE TITLE
让负属性变成正属性

### ISSUE THREAD

**Issue by zihaoshijie** [Iseason2000/DeEnchantment#27]
我突发奇想，如果这个插件能不能加一个物品或者让一个原版物品有一个特殊属性或者可以自定义一个物品，这个物品可以让负属性变成正属性，同理也可以加一个物品让他把正属性变成负属性。
因为现在箱子里负buff的东西确实有一点点多，所以我想出这个创意，不知作者能不能接受

**Comment by Iseason2000** [comment]
我可以提供让负魔转为正魔的命令，至于用不用由服主考虑

**Comment by zihaoshijie** [comment]
我觉得可以

**Comment by Iseason2000** [comment]
我在最新的2.0.6版本中修复了可能吃附魔的bug https://github.com/Iseason2000/DeEnchantment/releases/tag/2.0.6
