### ISSUE TITLE
服务器在启动时候默认加载全部附魔

### ISSUE THREAD

**Issue by xyfwdy** [Iseason2000/DeEnchantment#28]
该问题仍然未被修复
版本v2.0.5
https://github.com/Iseason2000/DeEnchantment/issues/24

**Comment by Iseason2000** [comment]
> 该问题仍然未被修复
> 版本v2.0.5
> https://github.com/Iseason2000/DeEnchantment/issues/24

请提供启动日志

**Comment by Iseason2000** [comment]
在我的测试中重复9次启动都未能复现问题（paper-1.19.1-99），请提供更多信息，或者把服务端打包过来
[logs.zip](https://github.com/Iseason2000/DeEnchantment/files/9274882/logs.zip)

**Comment by RanWhite** [comment]
> 在我的测试中重复9次启动都未能复现问题（paper-1.19.1-99），请提供更多信息，或者把服务端打包过来 [logs.zip](https://github.com/Iseason2000/DeEnchantment/files/9274882/logs.zip)

经过测试，在服务器启动的时候显示是正常的
![)T`VUVHOJWDL1I7J90ODC)R](https://user-images.githubusercontent.com/69817107/183256118-eb34823f-4f25-4175-ad0f-95cb89e82ce1.png)
但是在玩家仍然可以获得已经关闭的附魔
发现很奇怪的我reload了一下发现
![image](https://user-images.githubusercontent.com/69817107/183256149-a381ce83-3777-480e-acad-41dc861c6b1f.png)
竟然又被注册了
但是我开了一个测试服务器却无法复现这个问题
貌似是触发什么事件之后导致这个附魔被重新启用

**Comment by Iseason2000** [comment]
> > 在我的测试中重复9次启动都未能复现问题（paper-1.19.1-99），请提供更多信息，或者把服务端打包过来 [logs.zip](https://github.com/Iseason2000/DeEnchantment/files/9274882/logs.zip)
> 
> 经过测试，在服务器启动的时候显示是正常的 ![)T`VUVHOJWDL1I7J90ODC)R](https://user-images.githubusercontent.com/69817107/183256118-eb34823f-4f25-4175-ad0f-95cb89e82ce1.png) 但是在玩家仍然可以获得已经关闭的附魔 发现很奇怪的我reload了一下发现 ![image](https://user-images.githubusercontent.com/69817107/183256149-a381ce83-3777-480e-acad-41dc861c6b1f.png) 竟然又被注册了 但是我开了一个测试服务器却无法复现这个问题 貌似是触发什么事件之后导致这个附魔被重新启用

从逻辑上来讲不会发生这样的情况，但是仍可以获得负魔是bug，下个版本修复

**Comment by Iseason2000** [comment]
2.0.7 修复了已禁用的负魔仍能获得的bug
https://github.com/Iseason2000/DeEnchantment/releases/tag/2.0.7

**Comment by zihaoshijie** [comment]
所以你到底禁用了哪些附魔 阿然
