### ISSUE TITLE
取消神速附魔，更改为冰矢

### ISSUE THREAD

**Issue by zihaoshijie** [Iseason2000/DeEnchantment#29]
神速附魔确实有一点外挂了，和机枪一样，咋说呢，他应该属于正buff,不属于负buff，应当划为绿色魔咒。而且也不是火矢的反义词，建议将神速附魔替代为冰矢（射速降低但射击成功可使目标缓慢V 1秒）

**Comment by Iseason2000** [comment]
冰矢 就描述来说与缓慢药水箭一致
正是做不到冰冻效果
或者使箭在水下速度加快（水矢）
我才想了个速度的

虽然不是很对应冰矢的负魔

如果你觉得太强可以在配置文件削弱

如有更多人提出不好的话我会尝试其他效果

**Comment by zihaoshijie** [comment]
建议可以这样统一削弱：消耗更多耐久 例如射击1发掉3耐久

**Comment by zihaoshijie** [comment]
顺带问一句，神速满级是1 还是5
因为像经验修补等1级 后面都没有I 这里也没有，但我看我们服务器有人有V级的

**Comment by Iseason2000** [comment]
> 顺带问一句，神速满级是1 还是5 因为像经验修补等1级 后面都没有I 这里也没有，但我看我们服务器有人有V级的

默认是2级。可以在神速的配置中更改，如果你开启了突破等级上限可以获得超过最大等级的负魔

**Comment by zihaoshijie** [comment]
那我想到了，冰矢的作用：既然是deenchantment，那么就应该有负面效果，玩家射出获得缓慢1秒并且自动扣0.5血（无视血量冻伤），如果射到了敌人，则敌人缓慢1.5秒

**Comment by Iseason2000** [comment]
> 那我想到了，冰矢的作用：既然是deenchantment，那么就应该有负面效果，玩家射出获得缓慢1秒并且自动扣0.5血（无视血量冻伤），如果射到了敌人，则敌人缓慢1.5秒

负魔，取谐音之意
并不是一定要负面效果
相反或者相对都可
如果你一定要这种效果可以找我定制

**Comment by Cherisss** [comment]
> 冰矢 就描述来说与缓慢药水箭一致 正是做不到冰冻效果 或者使箭在水下速度加快（水矢） 我才想了个速度的
> 
> 虽然不是很对应冰矢的负魔
> 
> 如果你觉得太强可以在配置文件削弱
> 
> 如有更多人提出不好的话我会尝试其他效果

(我不懂这方面我只是提一嘴，我记得authme在玩家未登录时实现禁止移动的效果本质上是给玩家了一个255还是多少的反正很高的减速buff，冰矢这个想法我觉得挺不错，如果要实现冰冻可以尝试给予等级超高的减速buff 几秒这样的，比如冰矢I是0.5秒, II是1秒)

**Comment by Iseason2000** [comment]
> 

authme 单纯的是禁用移动，比药水简单粗暴
只是减速buff的话原版的缓慢药水箭也能做到，所以不在考虑中

**Comment by Iseason2000** [comment]
> > 冰矢 就描述来说与缓慢药水箭一致 正是做不到冰冻效果 或者使箭在水下速度加快（水矢） 我才想了个速度的
> > 虽然不是很对应冰矢的负魔
> > 如果你觉得太强可以在配置文件削弱
> > 如有更多人提出不好的话我会尝试其他效果
> 
> (我不懂这方面我只是提一嘴，我记得authme在玩家未登录时实现禁止移动的效果本质上是给玩家了一个255还是多少的反正很高的减速buff，冰矢这个想法我觉得挺不错，如果要实现冰冻可以尝试给予等级超高的减速buff 几秒这样的，比如冰矢I是0.5秒, II是1秒)

authme 单纯的是禁用移动，比药水简单粗暴
只是减速buff的话原版的缓慢药水箭也能做到，所以不在考虑中 @Cherisss

**Comment by zihaoshijie** [comment]
嗯
