### ISSUE TITLE
设置权限不生效

### ISSUE THREAD

**Issue by xyfwdy** [Iseason2000/DeEnchantment#30]
**插件版本** :  2.0.9
**服务端版本**: paper 1.19.2

**bug描述**
已经禁用的附魔该玩家仍然能使用 

**报错截图**
![EGL0(55 PXO@4)4`{ U` ~O](https://user-images.githubusercontent.com/69817107/190904716-834488b8-fcc3-47fd-924f-83b50133e622.png)
![OMZE}D`~CQWTJH (DS(@B3J](https://user-images.githubusercontent.com/69817107/190904717-786f6b72-35c8-460c-a556-c7d4393cb4da.png)
![6M9_)O0K%6X(PHZ}VM7EH_X](https://user-images.githubusercontent.com/69817107/190904714-dfeafb44-060b-4a6a-8e0a-fb3ae98b45ac.png)

**Comment by Iseason2000** [comment]
请现在config.yml中开启权限检查
