### ISSUE TITLE
建议灵魂绑定换个名字

### ISSUE THREAD

**Issue by CuteLittleSky** [Iseason2000/DeEnchantment#33]
**详细描述**

灵魂绑定容易使玩家造成误解,及死亡时该物品不会掉落..  

虽然我也把这个图片贴出来了,但就是不看...🙈🙈🙈  

至少有五六个人因为理解错功能来找我要求补偿物品了...

![4279c492de5bc61d](https://user-images.githubusercontent.com/62592731/212527110-a91ee1c3-6dd2-423a-9d12-0993cb0ea4aa.png)

**Comment by Iseason2000** [comment]
请自行在 de_binding_curse.yml 中修改灵魂绑定名称，同时可以在config.yml中 将 allowDescription 开启，将会在负魔下面显示负魔描述
如需保护玩家物品可以使用 SakuraBind https://www.mcbbs.net/thread-1406639-1-1.html

**Comment by CuteLittleSky** [comment]
> 请自行在 de_binding_curse.yml 中修改灵魂绑定名称，同时可以在config.yml中 将 allowDescription 开启，将会在负魔下面显示负魔描述 如需保护玩家物品可以使用 SakuraBind https://www.mcbbs.net/thread-1406639-1-1.html

感谢,改名后改名前的附魔还能用吗

**Comment by Iseason2000** [comment]
> > 请自行在 de_binding_curse.yml 中修改灵魂绑定名称，同时可以在config.yml中 将 allowDescription 开启，将会在负魔下面显示负魔描述 如需保护玩家物品可以使用 SakuraBind https://www.mcbbs.net/thread-1406639-1-1.html
> 
> 感谢,改名后改名前的附魔还能用吗

可以的

**Comment by CuteLittleSky** [comment]
> > > 请自行在 de_binding_curse.yml 中修改灵魂绑定名称，同时可以在config.yml中 将 allowDescription 开启，将会在负魔下面显示负魔描述 如需保护玩家物品可以使用 SakuraBind https://www.mcbbs.net/thread-1406639-1-1.html
> > 
> > 
> > 感谢,改名后改名前的附魔还能用吗
> 
> 可以的

话说这个附魔有死亡不掉落的效果吗...
有时候似乎有有时候又没有

**Comment by Iseason2000** [comment]
> > > > 请自行在 de_binding_curse.yml 中修改灵魂绑定名称，同时可以在config.yml中 将 allowDescription 开启，将会在负魔下面显示负魔描述 如需保护玩家物品可以使用 SakuraBind https://www.mcbbs.net/thread-1406639-1-1.html
> > > 
> > > 
> > > 感谢,改名后改名前的附魔还能用吗
> > 
> > 可以的
> 
> 话说这个附魔有死亡不掉落的效果吗...
> 有时候似乎有有时候又没有
> 服务器没加其他附魔插件

有，但可能存在问题，具体如何我也忘了，之后再检查一下

**Comment by Iseason2000** [comment]
死亡不掉落已在最新版本中修复

**Comment by CuteLittleSky** [comment]
> 死亡不掉落已在最新版本中修复

感谢qaq
原本还想说ecoenchants装上会导致负魔不显示结果就修了23333
