### ISSUE TITLE
附魔描述无法显示

### ISSUE THREAD

**Issue by Qian-F** [Iseason2000/DeEnchantment#36]
**插件版本** :  2.1.3
**服务端版本**: purpur-1.18.2-1632

**bug描述**
游戏中无法显示附魔描述

**报错截图**

![image.png](https://s2.loli.net/2023/01/29/IFSUzuWsL8prDRy.png)

**Comment by Iseason2000** [comment]
![image](https://user-images.githubusercontent.com/65019366/215322191-b862e5d8-c4dd-4f04-93d9-927c643092b0.png)
未能复现，请确保 config.yml 中的 allowDescription 设置为 true 且正确重载

**Comment by Qian-F** [comment]
> ![image](https://user-images.githubusercontent.com/65019366/215322191-b862e5d8-c4dd-4f04-93d9-927c643092b0.png)
> 未能复现，请确保 config.yml 中的 allowDescription 设置为 true 且正确重载

服务端使用1.18.2purper  
客户端使用fabric最新版本
再试试  如果无法复现那就是服务端插件问题

**Comment by Iseason2000** [comment]
> 

测试环境为 
服务端 : purpur-1.18.2-1632 
插件：DeEnchantment-2.1.3 只有一个
负魔描述正常出现，服务端插件与客户端无关

**Comment by Qian-F** [comment]
> > 
> 
> 测试环境为 
> 服务端 : purpur-1.18.2-1632 
> 插件：DeEnchantment-2.1.3 只有一个
> 负魔描述正常出现，服务端插件与客户端无关
> 

只有一个正常？  是不是要修复一下

**Comment by Iseason2000** [comment]
测试环境为
服务端 : purpur-1.18.2-1632
插件：DeEnchantment-2.1.3 只有一个
负魔描述正常出现，服务端插件与客户端无关

只有一个正常？ 是不是要修复一下
> 

只有一个插件的情况下一切正常，如果你有什么插件导致异常请自行排查

**Comment by Qian-F** [comment]
> 只有一个插件的情况下一切正常，如果你有什么插件导致异常请自行排查
> 

噢噢好的谢谢  请问一下这个描述是如何实现的呢

**Comment by Iseason2000** [comment]
> > 只有一个插件的情况下一切正常，如果你有什么插件导致异常请自行排查
> 
> 噢噢好的谢谢 请问一下这个描述是如何实现的呢

描述与负魔名称一样都是lore。只要能显示负魔名称，你的设置正确，那就一定能显示描述
