### ISSUE TITLE
附魔连珠后会无限射箭

### ISSUE THREAD

**Issue by mjiangmc** [Iseason2000/DeEnchantment#37]
**插件版本** :  2.1.4
**服务端版本**: purpur-1.19.3-383

**bug描述**
附魔连珠后会无限射箭
**重现步骤**
1. 弓箭附魔连珠

[报错.txt](https://github.com/Iseason2000/DeEnchantment/files/10568065/default.txt)
![QQ截图20230202185120](https://user-images.githubusercontent.com/63889583/216305184-261a273d-820c-4388-a288-41c4cb727988.png)

**其他信息**

**Comment by Iseason2000** [comment]
已修复 2.1.5
