### ISSUE TITLE
加载时报错自动关服

### ISSUE THREAD

**Issue by DongShaoNB** [Iseason2000/DeEnchantment#38]
**插件版本** :  2.1.5
**服务端版本**: purpur-1.19.3-1908.jar

**bug描述**
启动服务器到加载DeEnchantment时报错关服

**重现步骤**
1. 直接启动服务器

**报错截图**
![QQ截图20230206095914.png](https://img.fastmirror.net/s/2023/02/06/63e05effab70a.png)

**其他信息**
首次启动或删除配置文件后启动不会触发

**Comment by Iseason2000** [comment]
请提供完整日志，附魔配置及插件列表

**Comment by DongShaoNB** [comment]
日志: https://paste.ubuntu.com/p/zBKrKWztzg/  
负魔配置是默认生成的 没有改动  
插件列表不方便提供，有使用EcoEnchants v9.16.1

**Comment by Iseason2000** [comment]
请尝试2.1.6版本

**Comment by DongShaoNB** [comment]
可以了
