### ISSUE TITLE
指令无用

### ISSUE THREAD

**Issue by Shizuri23** [Iseason2000/DeEnchantment#4]
<img width="426" alt="image" src="https://user-images.githubusercontent.com/46082179/145418054-cffd3c1f-b6e8-4eeb-8a42-716b14cb4a12.png">
<img width="375" alt="image" src="https://user-images.githubusercontent.com/46082179/145418085-fa3a58d8-d934-4bea-9b80-602029a5997a.png">
后台无反应
<img width="552" alt="image" src="https://user-images.githubusercontent.com/46082179/145418119-cf529a8e-39b8-4c60-b6cb-92019825d723.png">

This server is running Paper version git-Paper-61 (MC: 1.18) (Implementing API version 1.18-R0.1-SNAPSHOT) (Git: 0e91b6a)

**Comment by Iseason2000** [comment]
插件在重启时有概率注册附魔失败，请输入de reload重新注册一下就可以了，如果无效请附上重置时的控制台信息

**Comment by Shizuri23** [comment]
> 你没有输入附魔的等级 ！

淦，是我傻了！

**Comment by AdminHcat** [comment]
> 你没有输入附魔的等级 ！ 应该为/de add 横扫失败 3

无命令反馈会引起用户困惑，建议增加消息反馈提示用户指令执行未成功的原因

**Comment by Iseason2000** [comment]
> > 你没有输入附魔的等级 ！ 应该为/de add 横扫失败 3
> 
> 无命令反馈会引起用户困惑，建议增加消息反馈提示用户指令执行未成功的原因

将在下个版本中添加该功能
