### ISSUE TITLE
与EcoEnchants的灵魂绑定冲突

### ISSUE THREAD

**Issue by CuteLittleSky** [Iseason2000/DeEnchantment#41]
`**插件版本**` :  2.1.9
**服务端版本**: purpur-1.20.1-2011

**bug描述**
如果一个装备同时打了负魔书与EcoEnchants的灵魂绑定,死了会给两份装备(不知道是不是冲突)

**Comment by CuteLittleSky** [comment]
> 冲突，关闭其中一个即可

不考虑加个判断关一下或者兼容一下吗qaq

毕竟写了兼容插件233

**Comment by Iseason2000** [comment]
> > 冲突，关闭其中一个即可
> 
> 不考虑加个判断关一下或者兼容一下吗qaq
> 
> 毕竟写了兼容插件233

下个版本
