### ISSUE TITLE
emm 配合EcoEnchants又显示不出lore了

### ISSUE THREAD

**Issue by Illusionika** [Iseason2000/DeEnchantment#5]
![FM](https://user-images.githubusercontent.com/46653839/146785653-708c6ea3-2513-4b1b-8e13-3184871b5c74.png)

如图所示，和之前的那个issues差不多

服务端版本Paper-1.18.1-82 
EcoEnchants版本8.14.30   
DeEnchantment版本1.1.2

都是最新版支持1.18.X

**Comment by Iseason2000** [comment]
付费插件的兼容请提供插件本体，可以加我QQ1347811744

**Comment by Iseason2000** [comment]
#2
