### ISSUE TITLE
geyser上基岩版使用的兼容性问题

### ISSUE THREAD

**Issue by Shizuri23** [Iseason2000/DeEnchantment#6]
在java上一切正常使用
在基岩版上无法把含有负魔的附魔书在铁砧上对武器/装备进行附魔
<img width="518" alt="image" src="https://user-images.githubusercontent.com/46082179/147390989-98ea6c42-9803-453e-82fe-ae907a447667.png">
这个是java版本的，是正常的
<img width="637" alt="image" src="https://user-images.githubusercontent.com/46082179/147391035-a10ded12-982d-43eb-bbf3-da3f4077a4ae.png">
这个是基岩版的，不能正常使用

**Comment by Iseason2000** [comment]
本插件不会对基岩版做出任何适配(不知道其中的原理)

**Comment by Iseason2000** [comment]
无法解决
