### ISSUE TITLE
疾行装备卸下后仍有buff

### ISSUE THREAD

**Issue by Shizuri23** [Iseason2000/DeEnchantment#7]
This server is running Purpur version git-Purpur-1436 (MC: 1.18.1) (Implementing API version 1.18.1-R0.1-SNAPSHOT) (Git: 
Previous version: git-Purpur-1454 (MC: 1.18.1)
<img width="191" alt="image" src="https://user-images.githubusercontent.com/46082179/147409173-d0037697-de1e-455a-a760-2c4938c1a742.png">
<img width="158" alt="image" src="https://user-images.githubusercontent.com/46082179/147409191-8659783a-7582-4c77-843a-93bacd36fdc6.png">
10秒之后自动补充，都脱下来了，去不掉这个效果

**Comment by Shizuri23** [comment]
重启之后就好了

**Comment by Iseason2000** [comment]
已在新版本中彻底杜绝
