### ISSUE TITLE
1.1.3版本仍然有疾行bug

### ISSUE THREAD

**Issue by Shizuri23** [Iseason2000/DeEnchantment#8]
![F316324123A0DAA1F28F178640497B9B](https://user-images.githubusercontent.com/46082179/148153913-b028e090-27a6-458c-a6ac-366ada30cd8c.png)
<img width="643" alt="image" src="https://user-images.githubusercontent.com/46082179/148153930-918b7894-ca16-464b-9fb9-604fda3808d5.png">

**Comment by Shizuri23** [comment]
有些缘故不能更新到最新的paper，如果最新的paper没有问题就当我放屁
麻烦作者了

**Comment by Iseason2000** [comment]
这次真的修复了
